packages:
  - 'packages/core'
  - 'packages/cli-node'
  - 'packages/cli-rust'
  - 'packages/cli-node-darwin-arm64'
  - 'packages/cli-node-darwin-x64'
  - 'packages/cli-node-linux-arm64'
  - 'packages/cli-node-linux-x64'
  - 'packages/cli-node-linux-arm64-musl'
  - 'packages/cli-node-linux-x64-musl'
